// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Client = require("react-dom/client");

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(React.createElement("div", undefined));
}

/* rootElement Not a pure module */
