// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function log(prim) {
  console.log(prim);
}

console.log("Hello, World!");

function add(x, y) {
  return x + y | 0;
}

console.log(25);

console.log(27);

function mul(x, y) {
  return Math.imul(x, y);
}

function doSomething(x, y) {
  var sum = x + y | 0;
  var multiply = Math.imul(x, y);
  return [
          sum,
          multiply
        ];
}

var prim = doSomething(123, 234);

console.log(prim);

var user = {
  name: "Rajesh Sahoo",
  age: 27,
  gender: "MALE"
};

console.log(user);

var newrecord = Caml_obj.obj_dup(user);

newrecord.gender = "";

newrecord.age = 26;

newrecord.name = "Rein Fred";

console.log(newrecord);

var num = 10;

var ageName = [
  "Rajesh Sahoo",
  27
];

var age = 27;

var newUser = newrecord;

exports.log = log;
exports.num = num;
exports.add = add;
exports.ageName = ageName;
exports.age = age;
exports.mul = mul;
exports.doSomething = doSomething;
exports.user = user;
exports.newUser = newUser;
/*  Not a pure module */
