// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Test(props) {
  return React.createElement("div", undefined, "Hello World");
}

var make = Test;

exports.make = make;
/* react Not a pure module */
